version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cockroach-backend
    env_file:
      - .env
    volumes:
      - ./src:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    networks:
      - game-network
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  nginx:
    image: nginx:alpine
    container_name: cockroach-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    networks:
      - game-network

  db:
    image: postgres:15
    container_name: cockroach-db
    env_file: .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "25432:5432"
    networks:
      - game-network

  redis:
    image: redis:7-alpine
    container_name: cockroach-redis
    command: redis-server
    env_file:
      - .env
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - game-network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  postgres-data:
  redis-data:

networks:
  game-network:
    driver: bridge